# Generated by Django 4.2.6 on 2023-10-20 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Event', max_length=150)),
                ('text', models.TextField(default='')),
                ('preview', models.ImageField(blank=True, upload_to='events_preview')),
                ('place', models.CharField(max_length=200)),
                ('coords', models.CharField(blank=True, max_length=100)),
                ('event_time', models.DateTimeField()),
                ('reg_time_end', models.DateTimeField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='events', to='events.tags')),
            ],
        ),
    ]
