# Generated by Django 4.2.6 on 2023-10-20 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_rename_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(null=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
