# Generated by Django 4.2.6 on 2023-10-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_participant_alter_event_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_time',
            new_name='event_time_start',
        ),
        migrations.AddField(
            model_name='event',
            name='event_time_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='reg_time_end',
            field=models.DateTimeField(null=True),
        ),
    ]
