# Generated by Django 4.2.6 on 2023-10-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_place_event_city_event_house_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='preview',
            field=models.ImageField(blank=True, default='events_preview/no_preview.jpg', upload_to='events_preview'),
        ),
    ]
