# Generated by Django 4.2.6 on 2023-10-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_price_alter_event_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='reg_time_end',
        ),
    ]
