# Generated by Django 4.2.6 on 2023-10-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='users_photos/no_photo.png', upload_to='users_photos'),
        ),
    ]
